### ISSUE TITLE
Tablas de verdad

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-nestor-diego-elisa#1]
[tablas de verdad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-nestor-diego-elisa/files/13221684/tablas.de.verdad.pdf)

**Comment by mayraglez917** [comment]
Portada: 25/25
Procedimiento: 25/25
Figuras, ilustraciones y fotografías: 17/25 (No contiene mínimo 10 figuras e ilustraciones del las actividades realizadas ).
Resultados y Conclusión: 25/25
Total: 92/100

Puntaje final: 18.4/20
Calificado por el equipo de Mayra, Diego, Félix, Daniel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
